#ifndef CONSTANTS_H
#define CONSTANTS_H

#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define JUMP_FORCE_DECREMENT 400
#define INITIAL_JUMP_FORCE 600
#define MOVEMENT_SPEED 200
#define MARIO_MAP_WIDTH 16 // tile units
#define MAP_HEIGHT 13
#define GRAVITY 300
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SCREENSHAKE_DURATION 0.25f
#define INJURED_TIME 2.5f
#define KOOPA_SPEED 80
#define INITIAL_JUMP_FORCE_SMALL 100
#define KOOPA_SPAWN_DELAY 7.0f
#define ANIMATION_DELAY 0.5f
#define MARIO_SCORE_TIME 8.0f
#define QUESTER_FRAME_TIME 0.5f
#define QUESTER_BASE_SPEED 1.5f
#define HATQUEST_TILE_SIZE 32
#define HATQUEST_MAP_WIDTH 80
#define LIFDOFF 250

#endif // !CONSTANTS_H